### PR TITLE
fix: Don't create link previews for links in code blocks

### LINKED ISSUE #776: Bug: Wire should not parse links within the code tags
Try to send the following message in Wire:

    ```
    Toast toast = Toast.makeText(this, "Hello", Toast.LENGTH_LONG);
    toast.show();
    ```

Expected: the message is sent formatted as code, nothing else is attached.
Actual: below the code a link to `http://toast.show` website is attached.

image

### PR DESCRIPTION
**Pull request by ffflorian**
This PR will
* disable link preview creation for links in code blocks, e.g. `this is my code on wire.com`
* fix #776

### CODE REVIEW

File: app/script/links/LinkPreviewHelpers.js [hunk 1]
```diff
@@ -22,16 +22,18 @@
 window.z = window.z || {};
 window.z.links = z.links || {};
 
+const codeBlockRegex = new RegExp('`(``)?[\\s\\S]*?`(``)?', 'gm');
```
Comment (AndyLnd) [inline app/script/links/LinkPreviewHelpers.js]:
```suggestion
const codeBlockRegex = /(`|```)[^]*?\1/gm
```

File: app/script/links/LinkPreviewHelpers.js [hunk 2]
```diff
@@ -22,16 +22,18 @@
 window.z = window.z || {};
 window.z.links = z.links || {};
 
+const codeBlockRegex = /(`|```)[^]*?\1/gm;
```
Comment (max-baz) [inline app/script/links/LinkPreviewHelpers.js:25]: @ffflorian thanks for the fix! I haven't tested it yet, but just want to confirm with you to be sure: code blocks aren't necessarily wrapped in one or three backticks, it could be four, five and more backticks. This works in Wire:

`````
````
aaa
```
bbb
````
`````

Comment (ffflorian) [reply app/script/links/LinkPreviewHelpers.js:25]: Ah, you are right. Will be fixed in https://github.com/wireapp/wire-webapp/pull/5201.
Thanks!
