### PR TITLE
fix: Add safeguard to platform checks

### LINKED ISSUE #3685: platform check failed on `TypeError: window.platform.os.family is null`
Hello.

Looks like my browser is failing checks at `app/script/util/Environment.js`:

```
window.platform.ua:
"Mozilla/5.0 (X11; DragonFly x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
window.platform.os.family:
null
```

Hence check on the line 77 in Environment.js breaks due to `windows.platform.os.family` being null.

I don't know whether it's fine to treat my platform as Linux, but I think it should work fine anyway.

### PR DESCRIPTION
**Pull request by gregor**
Fixes #3685

### CODE REVIEW

File: app/script/util/Environment.js [hunk 1]
```diff
@@ -62,7 +62,8 @@ z.util.Environment = (() => {
   };
 
   const _getVersion = () => {
-    const [majorVersion] = window.platform.version.split('.');
+    const browserVersion = window.platform.version || [];
+    const [majorVersion] = browserVersion.split('.');
```
Comment (atomrc) [inline app/script/util/Environment.js]: Array doesn't have a method `split`. Should be defaulting to an empty string.

Also you could inline it
```
const [majorVersion] = (window.platform.version || '').split('.');
```
