### PR TITLE
fix: Link embedding

### LINKED ISSUE #529: Soundcloud links validation
https://soundcloud.com/charts/top — is not treated as valid link. Wire tries to generate composition preview.

### PR DESCRIPTION
**Pull request by ffflorian**
This PR will
* add link preview rendering for static SoundCloud, YouTube, Vimeo and Spotify pages
* allow embedding all vimeo channel videos, not only from staff picks
* close #529

### CODE REVIEW

File: test/unit_tests/links/LinkPreviewBlackListSpec.js [hunk 1]
```diff
@@ -25,36 +25,66 @@ describe('is_blacklisted', () => {
...
-  it('should return true if link is vimeo', () => {
-    const url = 'vimeo.com';
+  it('should return false if link is Spotify static', () => {
+    const url = 'https://www.spotify.com/en/legal';
 
-    expect(z.links.LinkPreviewBlackList.isBlacklisted(url)).toBeTruthy();
+    expect(z.links.LinkPreviewBlackList.isBlacklisted(url)).toBe(false);
+  });
+
+  it('should return true if link is SoundCloud', () => {
```
Comment (bennycode) [inline test/unit_tests/links/LinkPreviewBlackListSpec.js]: Let's phrase these a little less technical:
```
 it('should return true if link is SoundCloud',
```
->
```
 it('blacklists SoundCloud links',
```

File: app/script/links/LinkPreviewBlackList.js [hunk 2]
```diff
@@ -23,9 +23,35 @@ window.z = window.z || {};
 window.z.links = z.links || {};
 
 z.links.LinkPreviewBlackList = (() => {
-  const BLACKLIST = ['soundcloud', 'spotify', 'youtu[.]?be', 'vimeo'];
+  const soundcloudStatic = [
```
Comment (bennycode) [inline app/script/links/LinkPreviewBlackList.js]: `soundcloudStatic` -> `soundCloudStatic`

Comment (AndyLnd) [reply app/script/links/LinkPreviewBlackList.js]: I would stick with florian's style, as soundcloud is a single name.

File: app/script/media/MediaEmbeds.js [hunk 3]
```diff
@@ -70,8 +70,8 @@ z.media.MediaEmbeds = (function() {
     // example: http://regexr.com/3ase5
     soundcloud: /(https?:\/\/(?:www\.|m\.)?)?soundcloud\.com(\/[\w-]+){2,3}/g,
```
Comment (atomrc) [inline app/script/media/MediaEmbeds.js:71]: Let's try to rely on this list to actually generate the linkPreview black list.

File: app/script/links/LinkPreviewBlackList.js (hunk 2 above)
Comment (bennycode) [reply app/script/links/LinkPreviewBlackList.js]: ...written with a capital C. 💃

File: app/script/media/MediaEmbeds.js (hunk 3 above)
Comment (ffflorian) [reply app/script/media/MediaEmbeds.js:71]: Unfortunately the regex needed is set in `MediaEmbeds`, but needed in `LinkPreviewBlacklist`.
Since `LinkPreviewBlacklist` is loaded before `MediaEmbeds`, we would need to change the order of loading these files. I am not sure which other implications that would have.
